name: pipeline

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request_target:
    branches: [main]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    name: Pipeline

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Docker Metadata
        id: metadata
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
          labels: |
            org.opencontainers.image.authors=Ben Smiley <ben@chatsdk.co> (@bensmiley)
            org.opencontainers.image.version=${{ env.GIT_DESCRIBE }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Available Platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Login to ghcr
        uses: docker/login-action@v1
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build NGINX Container
        id: build_nginx
        uses: docker/build-push-action@v2
        with:
          context: .
          file: deploy/nginx/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}

      - name: Build PHPFPM Container
        id: build_phpfpm
        uses: docker/build-push-action@v2
        with:
          context: .
          file: deploy/phpfpm/Dockerfile
          platforms: linux/amd64,linux/arm64
          build-args: |
            BUILD_PHP=${{ github.ref_type == 'tag' && steps.metadata.outputs.tags || '' }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
      
      - name: Container Digests
        run: |
          echo ${{ steps.build_nginx.outputs.digest }}
          echo ${{ steps.build_phpfpm.outputs.digest }}
